---
- name: Manage windows servers
  hosts: win
  tasks:

  - name: Create directory structure
    win_file:
      path: C:\Temp\folder
      state: directory

  - name: test powershell
    win_shell: |
              get-host
    register: result_get_host

  - name: display result_get_host
    debug:
      var: result_get_host

  - name: add directory
    win_file:
      path: C:\Users\Administrator\VisualStudio
      state: directory

  - name: Download the Visual Studio installer
    win_get_url:
      url: https://go.microsoft.com/fwlink/?LinkID=620884
      dest: C:\Users\Administrator\Desktop\VisualStudio\VSCodeSetup.exe
      force: true

  - name: Install VSC
    win_package:
      path: C:\Users\Administrator\Desktop\VisualStudio\VSCodeSetup.exe
      state: present

  - name: Download the .NET SDK installer
    win_get_url:
      url: https://download.visualstudio.microsoft.com/download/pr/90b0cc31-08be-4b6a-8968-e7e218f3a2aa/df81c3fadb7b2b6d874515d595f91123/dotnet-sdk-3.1.412-win-x64.exe
      dest: C:\Users\Administrator\Desktop\dotnet\dotnet-sdk.exe
      force: true

  - name: Install .NET SDK
    win_package:
      path: C:\Users\Administrator\Desktop\dotnet\dotnet-sdk.exe
      state: present